### ISSUE TITLE
No such file or directory: 'ffprobe'

### ISSUE THREAD

**Issue by FlingYourself** [Firepal/stammer#12]
Here is the error I got:
westonfleck@Westons-iMac ~ % python3 stammer.py steamedhams.mp3 ohthemisery.mp3 question.mp3
Traceback (most recent call last):
  File "/Users/westonfleck/stammer.py", line 254, in <module>
    main()
  File "/Users/westonfleck/stammer.py", line 247, in main
    process(carrier_path, modulator_path, output_path)
  File "/Users/westonfleck/stammer.py", line 143, in process
    carrier_type = file_type(carrier_path)
  File "/Users/westonfleck/stammer.py", line 58, in file_type
    return subprocess.run(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe'

**Comment by GFJHogue** [comment]
This is the same thing as #6, but on macOS.

You should verify that you have ffmpeg and ffprobe properly installed (ie. in your `Path`).
If they're installed properly, these commands won't give any error: `which ffmpeg` and `which ffprobe`.
