### ISSUE TITLE
File not found issue

### ISSUE THREAD

**Issue by jaidon-thezombie** [Firepal/stammer#35]
I am inputting the following

stammer.py "C:\Users\teamn\OneDrive\Documents\Steamed_Hams.mp4" "C:\Users\teamn\OneDrive\Documents\Disciple.mp3" "C:\Users\teamn\OneDrive\Documents\stammer-main\outputs\test.mp4"

and everytime i have inputted this i get back this

Traceback (most recent call last):
  File "C:\Users\teamn\OneDrive\Documents\stammer-main\stammer.py", line 372, in <module>
    main()
  File "C:\Users\teamn\OneDrive\Documents\stammer-main\stammer.py", line 368, in main
    process(**vars(args))
  File "C:\Users\teamn\OneDrive\Documents\stammer-main\stammer.py", line 264, in process
    raise FileNotFoundError(f"Carrier file {carrier_path} not found.")
FileNotFoundError: Carrier file C:\Users\teamn\OneDrive\Documents\Steamed_Hams.mp4 not found."

am i doing something wrong here?

Edit: Moving the files to different folders also produces the same error

Edit 2: I do in fact have ffmpeg installed

**Comment by hello10293** [comment]
Try putting everything (including the video and python file) in the same folder, then open up powershell, then type [code]python stammer Steamed_Hams.mp4 Disciple.mp3 test.mp4[/code]
