### ISSUE TITLE
Python 3.x typed vars crash

### ISSUE THREAD

**Issue by jayahayajg** [Firepal/stammer#66]
Traceback (most recent call last):
  File "C:\Users\jspar\Downloads\stammer-main\stammer-main\stammer.py", line 20, in <module>
    import video_out
  File "C:\Users\jspar\Downloads\stammer-main\stammer-main\video_out.py", line 2, in <module>
    from decay_cache import DecayCache
  File "C:\Users\jspar\Downloads\stammer-main\stammer-main\decay_cache.py", line 13, in <module>
    class DecayCache:
  File "C:\Users\jspar\Downloads\stammer-main\stammer-main\decay_cache.py", line 14, in DecayCache
    items: dict[DecayItem] = {}
TypeError: 'type' object is not subscriptable

**Comment by Firepal** [comment]
What is your python version? 
Use `python3 --version`

**Comment by MDTravisYT** [comment]
I'm getting the same error. Here's the version along with the error output:
```root@[computer]:[folder]# python3 stammer.py in1.mp4 in2.mp4 out.mp4
Traceback (most recent call last):
  File "stammer.py", line 20, in <module>
    import video_out
  File "[folder]/video_out.py", line 2, in <module>
    from decay_cache import DecayCache
  File "[folder]/decay_cache.py", line 13, in <module>
    class DecayCache:
  File "[folder]/decay_cache.py", line 14, in DecayCache
    items: dict[DecayItem] = {}
TypeError: 'type' object is not subscriptable
root@[computer]:[folder]# python3 --version
Python 3.8.10
root@[computer]:[folder]#```

**Comment by Firepal** [comment]
Python 3.9 typing is creating a whole BUNCH of errors... i think it will have to be removed. Python doesn't even do true type-checking.

**Comment by Firepal** [comment]
This data structure has been entirely replaced.
